#!/usr/bin/env python3 
'''
Supplies a function for calculating Observed/Expected values over pairwise combinations of segments.

Input format for the data file:

p a t a
p i k u b e
s a mb u k i
k a tʃ o
...

Input format for the segment list:

"seg1 seg2 seg3"

(e.g., "a e i o u" or "ph t tʃ")

The OE() function will print a table of pairwise OE calculations in Terminal or save it to a file in the location you specify; see doc entry for "OE" for details.

Example use:

OE("LearningData.txt", "p k t")

For additional options, from python3, type "help(oecalc)" or "help(OE, oecalc)"

'''

# LICENSE: Released under the FreeBSD license. 
# http://www.freebsd.org/copyright/freebsd-license.html




from itertools import product
 
def pairOEcalc(filepath, segs, rndparam=2):
	'''
	filepath is a path to the file you want to calculate O/E over.
	formatting: same as the input to Hayes and Wilson's UCLA Phonotactic Learner, only this can deal with Unicode

	p a t a
	p i k u b e
	s a mb u k i

	segs is the list of segbols you want to evaluate for Observed/Expected. separate it by spaces and surround by quotes, "e i o"
	O/E is calculated as follows:
	Expected: N(S1) * N(S2)/ N of all pairs
	Observed: N(S1S2)
	the function will return unrounded OE, as well as a value rounded to the parameter given by the "rounded" argument.
	Defaults to 2, so an O/E value of 1.3432 will be printed as 1.34.
	'''
	try:
		words = open(filepath, 'r', encoding='utf-8').readlines()
	except FileNotFoundError:
		print("please make sure there is a file to read at the location.")
		pass
	seglist = segs.strip().split(' ')
	wordlist = [x.strip().split() for x in words]
	pairs = {}.fromkeys(''.join(list(x)) for x in product(seglist, repeat=2)) #creates a dictionary with S1,S2 pairs from seglist, every possible combination
	segs = {}.fromkeys(seglist, 0)
	for x in pairs:
		pairs[x] = {'observed':0, 'expected':0}
	paircount = 0
	for word in wordlist:
		word = [x for x in word if x in seglist]
		if len(word)<2:
			continue
		else:
			segpairsinword = [word[x]+word[x+1] for x in range(0, len(word)-1)] #a list of 2-seg pairs in the word
		paircount += len(segpairsinword)
		for pair in segpairsinword:
			joined = ''.join(pair)
			pairs[joined]['observed']+=1
		for seg in word:
			segs[seg] += 1
	for pair in pairs:
		seg1,seg2 = pair[0],pair[1]
		pairs[pair]['expected'] = segs[seg1]*segs[seg2]/paircount
		pairs[pair]['OE'] = pairs[pair]['observed']/pairs[pair]['expected']
		pairs[pair]['OErnd']=round(pairs[pair]['OE'],rndparam)
	return(pairs)

def makeOETable(pairsdic, segs, rounded=True, prnt=True, outfile="None"):
	'''
	arranges the O/E values and sorts them into a table for display.
	"prnt" defaults to "True"; the function will print the results to screen.
	the default rounding parameter is 2 (e.g., 0.34122 gets printed as 0.34)
	if you want something different, set "rounded" to "False"
	'''
	seglist = segs.strip().split(' ')
	header = '\t'+'\t'.join(seglist)
	if outfile!="None":
		f = open(outfile, 'w', encoding="utf-8")
	rows = [header]
	for seg in seglist:
		row = [seg]
		rndrow = [seg]
		for otherseg in seglist:
			pair = seg+otherseg
			row.append(str(pairsdic[pair]['OE']))
			rndrow.append(str(pairsdic[pair]['OErnd']))
		if rounded == False:
			outrow = '\t'.join(row)
		else:
			outrow = '\t'.join(rndrow)
		rows.append(outrow)
	if print:
		for row in rows:
			print(row)
	if outfile!="None":
		[f.write(row+'\n') for row in rows]
		f.close()

def OE(filepath, segs, prnt=True, outfile="None", rndparam=2):
	'''
	filepath is where your wordlist is located. Absolute path might be best here
	segs is the list of segments, space-separated, over which you want O/E calculated
	prnt (True, False) defines whether the table is printed to terminal stdout
	outfile is either "None" or a path to the file where you want the results saved.
	rndparam determines the rounding parameter for the O/E value that you see printed to screen or saved to file. Default is 2 decimals, e.g., 0.34122 will be printed as 0.34
	'''
	if rndparam!=2:
			rounded=False
	else:
			rounded=True
	pairsdic = pairOEcalc(filepath, segs, rndparam)
	makeOETable(pairsdic, segs, rounded, prnt, outfile)



if __name__ == "__main__":
	import sys
	rndparam=2
	prnt=True
	if len(sys.argv)==1:
		print("you need to supply some arguments to oecalc. please see the README.md on http://github.com/gouskova/oecalc for help and use instructions.")
	elif len(sys.argv)>1:
		filepath=sys.argv[1]
		segs = sys.argv[2]
	if len(sys.argv)>3:
		rndparam=sys.argv[3]
	if len(sys.argv)>4:
		prnt=sys.argv[4]
	if len(sys.argv)>5:
		print("too many arguments passed to oecalc--check spaces, maybe?")
	OE(filepath, segs, rndparam, prnt)
